it:
    languageLabel: Italiano
    contentDir: content/it
    pagination:
        path: pagina
    weight: 1

en:
    languageLabel: English
    contentDir: content/en
    pagination:
        path: page
    weight: 2
