includeNewer: true
threshold: 60
toLower: true

indices:

    - name: tags
      type: basic
      applyFilter: false
      cardinalityThreshold: 0
      pattern: ""
      toLower: false
      weight: 90

    - name: categories
      type: basic
      applyFilter: false
      cardinalityThreshold: 0
      pattern: ""
      toLower: false
      weight: 90

    - name: date
      type: basic
      applyFilter: false
      cardinalityThreshold: 0
      pattern: ""
      toLower: false
      weight: 10

    - name: fragmentref
      type: fragments
      applyFilter: true
      weight: 80
